PharmacyInterventions/PI.Web/Models/ContributionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PI.Models;

namespace PI.Web.Models
{
    public class ContributionViewModel
    {
        public ContributionViewModel()
        {
            IsValid = true;
            ContributionTypeCategoryId = 1;
        }

        // any response that goes back to the user around created/updated contributions
        public ContributionResponseViewModel Response { get; set; }

        // the contribution being created/edited
        public Contribution Contribution { get; set; }

        public int ContributionTypeCategoryId { get; set; }

        // for populating the dropdowns
        public SelectList Wards { get; set; }
        public SelectList Pharmacists { get; set; }
        public SelectList Medications { get; set; }
        public SelectList ContributionTypeCategories { get; set; }
        public IEnumerable<ContributionType> ContributionTypes { get; set; }
        public SelectList Outcomes { get; set; }
        public SelectList Stages { get; set; }
        public SelectList StaffTypes { get; set; }
        public SelectList TimeFrames { get; set; }
        
        // we got any errors
        public bool IsValid { get; set; }
    }

    // object to hold details around the contribution just added/updated
    public class ContributionResponseViewModel
    {
        public Contribution UpdatedContribution { get; set; }

        public bool WasNew { get; set; }

        public bool CreatingAnother { get; set; }
    }
}

PharmacyInterventions/PI.Web/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PI.Business;

namespace PI.Web.Controllers
{
    public class AjaxController : Controller
    {

        public JsonResult ValidNhi(string nhi)
        {
            bool valid = false;

            var valiationService = new ValidationService();
            valid = valiationService.ValidateNhi(nhi);

            return Json(new
            {
                valid
            }, JsonRequestBehavior.AllowGet);
        }

    }
}

PharmacyInterventions/PI.Web/Controllers/ContributionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataTables.Mvc;
using PI.Business;
using PI.Models;
using PI.Web.Extensions;
using PI.Web.Lookups;
using PI.Web.Models;

namespace PI.Web.Controllers
{
    public class ContributionController : Controller
    {
        private readonly ContributionService _contributionService;
        private readonly WardService _wardService;
        private readonly LookupService _lookupService;

        public ContributionController()
        {
            _contributionService = new ContributionService();
            _wardService = new WardService();
            _lookupService = new LookupService();
        }

        public ActionResult Index()
        {
            var model = new ContributionIndexViewModel
            {
                Contributions = _contributionService.GetAllContributions()
            };
            return View(model);
        }

        public ActionResult ContributionRecords([ModelBinder(typeof(DataTablesBinder))] IDataTablesRequest requestModel)
        {
            var service = new ContributionService();

            var allContributions = service.GetAllContributions();

            // apply filter
            IEnumerable<Contribution> filteredContributions;
            string searchValue = requestModel.Search.Value;
            if (!string.IsNullOrEmpty(searchValue))
            {
                filteredContributions = allContributions
                         .Where(c => c.Nhi.Contains(searchValue, StringComparison.CurrentCultureIgnoreCase) ||
                            c.Ward.Name.Contains(searchValue, StringComparison.CurrentCultureIgnoreCase) ||
                            c.Id.ToString().Contains(searchValue, StringComparison.CurrentCultureIgnoreCase) ||
                            c.Date.ToString("dd/MM/yyyy HH:mm").Contains(searchValue, StringComparison.CurrentCultureIgnoreCase) ||
                            c.Pharmacist.Name.Contains(searchValue, StringComparison.CurrentCultureIgnoreCase));
            }
            else
            {
                filteredContributions = allContributions;
            }

            //// sorting
            var sortedColumns = requestModel.Columns.GetSortedColumns();
            var isSorted = false;
            foreach (var column in sortedColumns)
            {
                Func<Contribution, string> orderingFunction = (c => column.Name == "Id" ? c.Id.ToString() :
                                                                    column.Name == "Nhi" ? c.Nhi :
                                                                    column.Name == "Ward" ? c.Ward.Name :
                                                                    column.Name == "Pharmacist" ? c.Pharmacist.Name :
                                                                    c.Date.ToString("yyyyMMddHHmm")); // fix me yyyyMMdd
                filteredContributions = column.SortDirection == Column.OrderDirection.Ascendant ? filteredContributions.OrderBy(orderingFunction) : filteredContributions.OrderByDescending(orderingFunction);
            }

            // paging
            var displayedContributions = filteredContributions
                                .Skip(requestModel.Start)
                                .Take(requestModel.Length);

            // convert to object datatable can understand
            //var result = from c in displayedContributions
            //             select new[] { Convert.ToString(c.Id), c.Nhi, c.Ward.Name, c.Pharmacist.Name, c.Date.ToString("dd/MM/yyyy HH:mm") };

            var result = from c in displayedContributions
                         select c.MapToJsonModel();

            return Json(new DataTablesResponse(requestModel.Draw, result, filteredContributions.Count(), allContributions.Count()), JsonRequestBehavior.AllowGet);
        }

        public void PopulateAdditionalContributionViewModelFields(ContributionViewModel model)
        {
            model.Pharmacists = new SelectList(_lookupService.GetAllPharmacists(), "Id", "Name");
            model.Wards = new SelectList(_wardService.GetAllWards(), "Id", "Name");
            model.Medications = new SelectList(_lookupService.GetAllMedications(), "Id", "Name");
            model.ContributionTypes = _contributionService.GetAllContributionTypes();
            model.Outcomes = new SelectList(_lookupService.GetAllOutcomes(), "Id", "Value");
            model.Stages = new SelectList(_lookupService.GetAllStages(), "Id", "Value");
            model.StaffTypes = new SelectList(_lookupService.GetAllStaffTypes(), "Id", "Value");
            model.TimeFrames = new SelectList(_lookupService.GetAllTimeFrames(), "Id", "Value");
        }

        [OutputCache(Duration = 0)]
        public ActionResult Edit(int? id, int? updatedContributionId, bool? created, int? createAnotherBasedOnId)
        {
            var service = new ContributionService();


            var model = new ContributionViewModel();
            if (updatedContributionId.HasValue)
            {
                var updatedContribution = service.GetContributionById(updatedContributionId.Value);
                model.Response = new ContributionResponseViewModel
                {
                    UpdatedContribution = updatedContribution,
                    WasNew = created.HasValue && created.Value,
                    CreatingAnother = createAnotherBasedOnId.HasValue
                };
            }

            PopulateAdditionalContributionViewModelFields(model);
            if (createAnotherBasedOnId.HasValue)
            {
                // we're creating a new one based on the past one
                var baseOnContribution = service.GetContributionById(createAnotherBasedOnId.Value);
                ModelState.Clear();
                model.Contribution = new Contribution
                {
                    Nhi = baseOnContribution.Nhi,
                    Date = baseOnContribution.Date,
                    PharmacistId = baseOnContribution.PharmacistId,
                    WardId = baseOnContribution.WardId
                };
            }
            else if (id.HasValue && !created.HasValue)
            {
                // we're editing an existing
                var contribution = service.GetContributionById(id.Value);
                model.Contribution = contribution;
            }
            else
            {
                // we're creating
                ModelState.Clear();
                model.Contribution = new Contribution
                {
                    Date = DateTime.Now
                };
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(ContributionViewModel model, FormCollection formCollection)
        {
            var service = new ContributionService();

            if (ModelState.IsValid)
            {
                Contribution updatedContribution;
                bool created = false;
                if (model.Contribution.Id != 0)
                {
                    var currentContribution = service.GetContributionById(model.Contribution.Id);
                    UpdateModel(currentContribution, "Contribution", formCollection);
                    service.SaveContribution(currentContribution);
                    updatedContribution = currentContribution;
                }
                else
                {
                    service.SaveContribution(model.Contribution);
                    updatedContribution = model.Contribution;
                    created = true;
                }
                int? createAnotherBasedOnId = null;
                if (formCollection["SubmissionType"] != null && formCollection["SubmissionType"] == ((int)SubmissionType.SaveAndAnotherForPatient).ToString())
                {
                    createAnotherBasedOnId = updatedContribution.Id;
                }
                return RedirectToAction("Edit", new { updatedContributionId = updatedContribution.Id, created, createAnotherBasedOnId });
            }

            // something wrong
            PopulateAdditionalContributionViewModelFields(model);
            model.IsValid = false;

            return View("Edit", model);
        }
    }
}

PharmacyInterventions/PI.Web/Views/Contribution/Edit.cshtml
@using System.Web.Configuration
@using PI.Web
@using PI.Web.Lookups
@model PI.Web.Models.ContributionViewModel

@{
    //Layout = "../Shared/PopupLayout.cshtml";
    Layout = null;
}


        <div>
            @if (Model.Response != null && Model.Response.UpdatedContribution != null)
            {
                <div class='ui-state-highlight ui-corner-all'>
                    <span class="ui-icon ui-icon-alert" style="float: left; margin-right:.3em;"></span>
                    <span>Contribution for <b>@Model.Response.UpdatedContribution.Nhi</b> at @Model.Response.UpdatedContribution.Date.ToString("dd/MM/yyyy HH:mm") was @(Model.Response.WasNew ? "created" : "edited").</span>
                </div>
                if (!Model.Response.CreatingAnother)
                {
                    <div class="dialog-buttons">
                        <a href="" class="close-dialog make-me-a-button" title="Close this dialog">Close this window</a>
                    </div>
                }
            }
        </div>
        @if (Model.Response == null || Model.Response.UpdatedContribution == null || Model.Response.CreatingAnother)
        {
         
            <div>
                @using (Html.BeginForm("Edit", "Contribution", FormMethod.Post))
                {
                    @Html.HiddenFor(i => i.Contribution.Id)
                    @Html.Hidden("SubmissionType", (int)SubmissionType.Save)
                    <div>
                        @{
                    if (!Model.IsValid)
                    {
                                <div class="ui-widget">
                                    <div class="ui-state-error ui-corner-all">
                                        @Html.ValidationSummary(false)
                                    </div>
                                </div>
                    }
                        }
                    
                        <div class="dialog-column dialog-column1">
                        
                            <div class="editor-label">
                                @Html.LabelFor(i => i.Contribution.Nhi)
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(i => i.Contribution.Nhi, new { @class = "nhi-entry" })
                                <span class="ui-widget nhi-validation-error has-tool-tip" title="You can continue, but NHI number is invalid" >
                                    <span class="ui-state-error ui-corner-all">Invalid NHI</span>
                                </span>
                            </div>
                            <div class="editor-label">
                                @Html.LabelFor(i => i.Contribution.Date)
                            </div>
                            <div class="editor-field">
                                @Html.TextBox("Contribution.Date", Model.Contribution.Date.ToString("dd/MM/yyyy HH:mm"))
                            </div>
                            <div class="editor-label">
                                @Html.LabelFor(i => i.Contribution.WardId)
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(i => i.Contribution.WardId, Model.Wards, "Select One")
                            </div>
                            <div class="editor-label">
                                @Html.LabelFor(i => i.Contribution.PharmacistId)
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(i => i.Contribution.PharmacistId, Model.Pharmacists, "Select One")
                            </div>

                        </div>

                        <div class="dialog-column dialog-column2">
                        
                            <div class="editor-label">
                                @Html.LabelFor(i => i.Contribution.MedicationId1)
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(i => i.Contribution.MedicationId1, Model.Medications, "Select One")
                            </div>
                            <div class="editor-label">
                                @Html.LabelFor(i => i.Contribution.MedicationId2)
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(i => i.Contribution.MedicationId2, Model.Medications, "Select One")
                            </div>
                            <div class="editor-label">
                                @Html.LabelFor(i => i.Contribution.ContributionTypeId)
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(i => i.Contribution.ContributionTypeId, new SelectList(Model.ContributionTypes, "Id", "Name"), new { @class = "contribution-id-type-dropdown" })

                            </div>
                
                        
                            <div class="editor-label">
                                @Html.LabelFor(i => i.Contribution.OutcomeId)
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(i => i.Contribution.OutcomeId, Model.Outcomes, "Select One")
                            </div>
                            <div class="editor-label">
                                @Html.LabelFor(i => i.Contribution.StageId)
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(i => i.Contribution.StageId, Model.Stages, "Select One")
                            </div>
                            <div class="editor-label">
                                @Html.LabelFor(i => i.Contribution.StaffInvolvedId)
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(i => i.Contribution.StaffInvolvedId, Model.StaffTypes, "Select One")
                            </div>
                            <div class="editor-label">
                                @Html.LabelFor(i => i.Contribution.TimeFrameId)
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(i => i.Contribution.TimeFrameId, Model.TimeFrames, "Select One")
                            </div>

                        </div>

                        <div class="dialog-column dialog-column3">
                        
                        
                            <div class="editor-label">
                                @Html.LabelFor(i => i.Contribution.Details)
                            </div>
                            <div class="editor-field">
                                @Html.TextAreaFor(i => i.Contribution.Details, new { @class = "contribution-details-input" })
                            </div>

                        </div>
                    



                


                    </div>
                    <div class="dialog-buttons">
                        <a href="" class="close-dialog" title="Close this dialog">Close</a>
                        @{
                                    int saveType = (int)SubmissionType.Save;
                                    int saveAndAnotherType = (int)SubmissionType.SaveAndAnotherForPatient;
                        }
                        <input type="button" id="save" name="save" value ="Save"  onclick="SubmitForm(this, @saveType)" class="make-me-a-button" />
                        <input type="button" id="saveAndAnother" name="saveAndAnother" value ="Save & another for NHI" title="Save this record and create another for the same patient" onclick="SubmitForm(this, @saveAndAnotherType)" class="make-me-a-button has-tool-tip" />
                    
                    </div>
                }
            </div>
       
        }

        <script type="text/javascript">

            function SubmitForm(btnClicked, submissionType) {
                $('#SubmissionType').val(submissionType);
                DoAjaxPost(btnClicked);
            }
            
            $(document).ready(function () {

                TurnJunkIntoButtons();

                GenerateToolTips();
                
                $('.close-dialog').on('click', function (event) {
                    $(this).closest('.ui-dialog-content').dialog('close');
                    event.preventDefault();
                    var $lmTable = $("#myDataTable").dataTable({ bRetrieve: true });
                    $lmTable.fnDraw();
                });
                
                // when the intervention type category changes then change the available intervention types
                $('.intervention-type-categories').change(function () {
                    PopulateInterventionTypeDropDown();
                });

                // on load populate the type drop down
                //PopulateInterventionTypeDropDown();

                // add datetime picker
                $('#Contribution_Date').datetimepicker();
                
                $(".nhi-entry").focusout(function () {
                    ValidateNhiNumber();
                });
                ValidateNhiNumber();
                
            });

            function ValidateNhiNumber() {
                $('.nhi-validation-error').hide();

                var nhiNumber = $(".nhi-entry").val();

                if (nhiNumber && nhiNumber != "") {
                    $.ajax({
                        type: "GET",
                        url: "@Url.Action("ValidNhi","Ajax")",
                            data: { nhi: nhiNumber },
                            error: function (xhr, status, error) {
                                //do something about the error  
                                alert("Attempting to validate nhi: " + error);
                            },
                            success: function (response) {
                                if (!response.valid) {
                                    $('.nhi-validation-error').css('display', 'inline-block');
                                }
                            }
                        });
                    }
            }

            // populates the intervention type dropdown based on the currently selected intervention type category
            function PopulateInterventionTypeDropDown() {
                $('.intervention-type-dropdown').hide();
                var currentCategoryId = $('.intervention-type-categories').val();
                //console.log(currentCategoryId);
                //$('#InterventionTypeCategory' + currentCategoryId).show();

                $('.intervention-id-type-dropdown').html($('#InterventionTypeCategory' + currentCategoryId).html());
            }



        </script>

PharmacyInterventions/PI.Web/Views/Contribution/Index.cshtml
@model PI.Web.Models.ContributionIndexViewModel
@{
    ViewBag.Title = "Contributions";
}


<div class="button-container">
    <a class="create-dialog-trigger" href="dialog">Create a new contribution</a>
</div>

<div id="contribution-edit-dialog" class="dialog-contents"></div>

<br/><br/>

<table id="myDataTable" class="display">
    <thead>
        <tr>
            <th>Date</th>
            <th>Nhi</th>
            <th>Detail</th>
            <th>Ward</th>
            <th>Pharmacist</th>
        </tr>
    </thead>
    <tbody> 
    </tbody>
</table>

@section scripts
{
    <script type="text/javascript">
        $(document).ready(function() {

            $('#myDataTable').dataTable({
                "jQueryUI": true,
                "serverSide": true,
                "ajax": "@Url.Action("ContributionRecords")",
                "processing": true,
                "pagingType": "full_numbers",
                "order": [[0, "desc"]],
                "columns": [
                    {
                        "name": "Date", "render": function (data, type, full, meta) {
                            var dateLink = '<span class="editable-contribution clickable" onclick="editItem(' + full.Id + ')" >' + full.Date + '</span>';
                            return dateLink;
                        }
                    },
                    {
                        "name": "Nhi",
                        "orderable": true, "data": "Nhi"
                    },
                    {
                        "name": "Details",
                        "orderable": false,
                        "render": function (data, type, full, meta) {
                            var intType = '<div class="details-category-and-type">' + full.ContributionType + '</div>';
                            var med1 = '<div class="details-field"><span class="details-field-label">Medication 1:</span><span class="details-field-value">' + full.Medication1 + '</span></div>';
                            var med2 = full.Medication2 ? '<div class="details-field"><span class="details-field-label">Medication 2:</span><span class="details-field-value">' + full.Medication2 + '</span></div>' : '';
                            var outcome = '<div class="details-field"><span class="details-field-label">Outcome:</span><span class="details-field-value">' + full.Outcome + '</span></div>';
                            var stage = '<div class="details-field"><span class="details-field-label">Stage:</span><span class="details-field-value">' + full.Stage + '</span></div>';
                            var staffInvolved = '<div class="details-field"><span class="details-field-label">Staff Involved:</span><span class="details-field-value">' + full.StaffInvolved + '</span></div>';
                            var timeTaken = '<div class="details-field"><span class="details-field-label">TimeTaken:</span><span class="details-field-value">' + full.TimeTaken + '</span></div>';
                            return '<div class="table-details">' + intType + '<div class="column1">' + med1 + med2 + '</div>' + '<div class="column2">' + outcome + stage + staffInvolved + timeTaken + '</div>' + '</div>';
                        }
                    },
                    { "name": "Ward", "data": "WardName" },
                    { "name": "Pharmacist", "data": "PharmacistName" }
                    
                ]
            });
        });

    </script>

    <script type="text/javascript">

        function editItem(id) {
            $('#contribution-edit-dialog').load("@Url.Action("Edit")?id=" + id, function() {
                $(this).dialog('open');
            });
            return false;
        }


        $(document).ready(function() {
            
            // hook up trigger to open the create intervention dialog - uses edit but passes no id
            $('.create-dialog-trigger').on('click', function(event) {
                $('#contribution-edit-dialog').load("@Url.Action("Edit")", function() {
                    $(this).dialog('open');
                });
                return false;
            });

            // create our edit/create dialog, but do not open it yet
            $('#contribution-edit-dialog').dialog({
                autoOpen: false,
                modal: true,
                width: 800,
                title: "Contributions"
            });


        });

    </script>
}