PharmacyInterventions/PI.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PI.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Pharmacy Interventions - Home Page";

            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Help()
        {

            return View();
        }
    }
}

PharmacyInterventions/PI.Web/Controllers/PharmacistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using PI.Business;
using PI.Models;
using PI.Web.Models;

namespace PI.Web.Controllers
{
    public class PharmacistController : Controller
    {
        //
        // GET: /Ward/

        public ActionResult Index()
        {
            var service = new PharmacistService();

            var model = new PharmacistIndexViewModel
                            {
                                Pharmacists = service.GetAllPharmacists(true)
                            };

            return View(model);
        }

        public ActionResult PharmacistList()
        {
            var model = CreatePharmacistIndexViewModel();

            return View("_PharmacistList", model);
        }

        [HttpPost]
        public ActionResult Index(Pharmacist newPharmacist, FormCollection formCollection)
        {
            var service = new PharmacistService();

            if (ModelState.IsValid)
            {
                // create the thing here
                newPharmacist.IsActive = true;
                service.CreatePharmacist(newPharmacist);
            } else
            {
                var model = CreatePharmacistIndexViewModel();
                model.IsValid = false;
                model.NewPharmacist = newPharmacist;
                return View("_PharmacistList", model);
            }


            return RedirectToAction("PharmacistList");
        }

        private PharmacistIndexViewModel CreatePharmacistIndexViewModel()
        {
            var service = new PharmacistService();

            var model = new PharmacistIndexViewModel
            {
                Pharmacists = service.GetAllPharmacists(true)
            };

            return model;
        }

        public JsonResult UpdatePharmacist(int pharmacistId, string pharmacistName, bool isActive, int? newIndex)
        {
            bool success = false;
            string errorMessage = "";

            var service = new PharmacistService();
            service.UpdatePharmacist(pharmacistId, pharmacistName, isActive);

            if(newIndex.HasValue)
                service.ReorderPharmacist(pharmacistId, newIndex.Value);

            success = true;

            return Json(new 
            {
                errorMessage,
                success
            }, JsonRequestBehavior.AllowGet);
        }

    }
}

PharmacyInterventions/PI.Web/Controllers/WardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using PI.Business;
using PI.Models;
using PI.Web.Models;

namespace PI.Web.Controllers
{
    public class WardController : Controller
    {
        //
        // GET: /Ward/

        public ActionResult Index()
        {
            var service = new WardService();

            var model = new WardIndexViewModel
                            {
                                Wards = service.GetAllWards(true)
                            };

            return View(model);
        }

        public ActionResult WardList()
        {
            var model = CreateWardIndexViewModel();

            return View("_WardList", model);
        }

        [HttpPost]
        public ActionResult Index(Ward newWard, FormCollection formCollection)
        {
            var service = new WardService();

            if (ModelState.IsValid)
            {
                // create the thing here
                newWard.IsActive = true;
                service.CreateWard(newWard);
            } else
            {
                var model = CreateWardIndexViewModel();
                model.IsValid = false;
                model.NewWard = newWard;
                return View("_WardList", model);
            }


            return RedirectToAction("WardList");
        }

        private WardIndexViewModel CreateWardIndexViewModel()
        {
            var service = new WardService();

            var model = new WardIndexViewModel
            {
                Wards = service.GetAllWards(true)
            };

            return model;
        }

        public JsonResult UpdateWard(int wardId, string wardName, bool isActive, int? newIndex)
        {
            bool success = false;
            string errorMessage = "";

            var service = new WardService();
            service.UpdateWard(wardId, wardName, isActive);

            if(newIndex.HasValue)
                service.ReorderWard(wardId, newIndex.Value);

            success = true;

            return Json(new 
            {
                errorMessage,
                success
            }, JsonRequestBehavior.AllowGet);
        }

    }
}

PharmacyInterventions/PI.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}



<div class="text-page">
    
    <h1>About</h1>

    This system has been created to aid in the capture of Pharmacy interventions and contributions.  It has been adapted from the EPIFANY system created by Rob Ticehurst.<br/><br/>
    Things that a missing from the system (an incomplete list):<br/>
    <ul>
        <li>a layout page for these text pages</li>
        <li>error handling on ajax calls</li>
        <li>general error handling - elmah!</li>
        <li>kpis</li>
        <li>reports - SSIS?</li>
        <li>the data tables could use some styling</li>
        <li>records in data tables - show more data and remove id column</li>
        <li>um dependancy injection</li>
        <li>well, you know, some sort of security ...</li>
    </ul>
</div>

PharmacyInterventions/PI.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

PharmacyInterventions/PI.Web/Views/Home/Help.cshtml
@{
    ViewBag.Title = "Help";
}

<div  class="text-page">
    <h1>Help</h1>
    Link to help files!
</div>

PharmacyInterventions/PI.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

<div class="container">
    <style>

    </style>
    <div class="imageContainer">
        <img src="@Url.Content("~/Images/PieSlicesTransparent.png")" id="fullPie" />
        <img src="@Url.Content("~/Images/PieSlice1.png")" id="pieSlice1" />
        <img src="@Url.Content("~/Images/PieSlice2.png")" id="pieSlice2" />
        <img src="@Url.Content("~/Images/PieSlice3.png")" id="pieSlice3" />
    </div>
    <div class="nameContainer">
        <div class="name">pi</div>
        <div class="nameFull1">Pharmacy</div>
        <div class="nameFull2">Interventions</div>
    </div>
    <div class="sectionContainer dataSectionContainer" data-sliceno="2">
        <div class="sectionName dataSectionName">DATA</div>
        <div class="sectionDivider">&nbsp;</div>
        <div class="sectionLinks">
            <div class="sectionLink"><a href="@Url.Action("Index","Intervention")">interventions</a></div>
            <div class="sectionLink"><a href="@Url.Action("Index","Contribution")">contributions</a></div>
            <div class="sectionLink"><a href="@Url.Action("Index","Kpi")">KPIs</a></div>
        </div>
    </div>
    <div class="sectionContainer helpSectionContainer" data-sliceno="1">
        <div class="sectionName dataSectionName">HELP</div>
        <div class="sectionDivider">&nbsp;</div>
        <div class="sectionLinks">
            <div class="sectionLink"><a href="@Url.Action("About","Home")">about</a></div>
            <div class="sectionLink"><a href="@Url.Action("Help","Home")">help</a></div>
        </div>
    </div>
    <div class="sectionContainer adminSectionContainer" data-sliceno="3">
        <div class="sectionName adminSectionName">ADMIN</div>
        <div class="sectionDivider">&nbsp;</div>
        <div class="sectionLinks">
            <div class="sectionLink"><a href="@Url.Action("Index","Pharmacist")">users</a></div>
            <div class="sectionLink"><a href="@Url.Action("Index","Ward")">wards</a></div>
            <div class="sectionLink">reports</div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function () {

        $('.sectionContainer').mouseenter(function () {
            var sliceNo = $(this).data('sliceno');
            var id = '#pieSlice' + sliceNo;
            $(id).fadeIn(500);
        });
        $('.sectionContainer').mouseleave(function () {
            var sliceNo = $(this).data('sliceno');
            var id = '#pieSlice' + sliceNo;
            $(id).fadeOut(500);
        });

    });

</script>